//Source: http://www.nextpoint.se/?p=447

var USERNAMES = [
	"Alvin",
	"Angelica Pickles",
	"Archie",
	"Arthur",
	"Astro",
	"Atom Ant",
	"Bamm-Bamm",
	"Barney Rubble",
	"Bart Simpson",
	"Batman",
	"Beetle Baily",
	"Betty Boop",
	"Blondie",
	"Boo Boo",
	"Boris Badenov",
	"Bugs Bunny",
	"Bullwinkle",
	"Calvin",
	"Captain America",
	"Cap'n Crunch",
	"Cartman",
	"Casper the Friendly Ghost",
	"Cat in the Hat",
	"Charlie Brown",
	"Charlie Tuna",
	"Chester Cheetah",
	"Chip and Dale",
	"Clifford the Big Red Dog",
	"Curious George",
	"Dagwood",
	"Daffy Duck",
	"Daphne",
	"Dennis the Menace",
	"Dick Tracy",
	"Dilbert",
	"Dino",
	"Donald Duck",
	"Dora the Explorer",
	"Droopy",
	"Dudley Dooright",
	"Eeyore",
	"Elmer Fudd",
	"Elroy Jetson",
	"Fat Albert",
	"Felix the Cat",
	"Flash",
	"Foghorn Leghorn",
	"Fred",
	"Fred Flintstone",
	"Frosty",
	"Garfield",
	"George of the Jungle",
	"Goofy",
	"Grape Ape",
	"Green Giant",
	"Grimm",
	"Grinch",
	"Hagar the Horrible",
	"Heckle and Jeckle",
	"Hello Kitty",
	"Hobbes",
	"Homer Simpson",
	"Huckleberry Hound",
	"Joe Camel",
	"Johnny Quest",
	"Josie and the Pussycats",
	"Jughead",
	"Lil' Abner",
	"Linus",
	"Lucy",
	"Magilla Gorilla",
	"Marmaduke",
	"Mickey Mouse",
	"Mighty Mouse",
	"Minnie Mouse",
	"Mr. Kool-Aid",
	"Mr. Magoo",
	"Muttley",
	"Nancy",
	"Natasha Fatale",
	"Olive Oyl",
	"Pebbles",
	"Pepe Le Pew",
	"Peter Pan",
	"Piglet",
	"Pig Pen",
	"Pink Panther",
	"Pluto",
	"Popeye",
	"Porky Pig",
	"Red Hot",
	"Ren and Stimpy",
	"Richie Rich",
	"Road Runner",
	"Rocky",
	"Roger Rabbit",
	"Sad Sack",
	"Scobby Doo",
	"Shaggy",
	"Sherman",
	"Smurfs",
	"Snap, Crackle and Pop",
	"Snidely Whiplash",
	"Snoopy",
	"Speed Buggy",
	"Speed Racer",
	"Spiderman",
	"SpongeBob SquarePants",
	"Squiddly Diddly",
	"Superman",
	"Sylvester",
	"The Professor",
	"Tigger",
	"Tinkerbell",
	"Tom and Jerry",
	"Tom Terrific",
	"Tony Tiger",
	"Toucan Sam",
	"Tweety Bird",
	"Underdog",
	"Velma",
	"Wile E. Coyote",
	"Wilma Flintstone",
	"Winnie the Pooh",
	"Wonder Woman",
	"Woodstock",
	"Woody Woodpecker",
	"Yogi Bear",
	"Pongo",
	"Roger",
	"Anita",
	"Perdita",
	"Cruella de Vil",
	"Tibbs",
	"Colonel",
	"Horace",
	"Jasper",
	"Flik",
	"Dot",
	"Princess Atta",
	"Hopper",
	"Molt",
	"P.T. Flea",
	"The Queen",
	"Heimlich",
	"Goofy",
	"Max Goof",
	"Pete",
	"Peg",
	"Pistol",
	"Pete Junior",
	"Chainsaw",
	"Aladdin",
	"Abu",
	"Genie",
	"Princess Jasmine",
	"Rajah",
	"Magic Carpet",
	"The Sultan",
	"Beast",
	"Belle",
	"Gaston",
	"Maurice",
	"Lumiere",
	"Mrs. Potts",
	"Cogsworth",
	"Chip",
	"Chick Hicks",
	"Lightning McQueen",
	"Mack",
	"Doc Hudson",
	"Sally Carrera",
	"The King",
	"Chicken Little",
	"Abby Mallard",
	"Runt",
	"Fish Out of Water",
	"Foxy Loxy",
	"Goosey Loosey",
	"Kirby",
	"Cinderella",
	"Lady Tremaine",
	"Drizella",
	"Anastasia",
	"Fairy Godmother",
	"Bruno",
	"Major",
	"Jaq",
	"Octavius (Gus)",
	"Prince Charming",
	"King of Duke",
	"Chip & Dale",
	"Fat Cat",
	"Gadget Hackwrench",
	"Monterey Jack",
	"Professor Norton Nimnul",
	"Zipper the Fly",
	"Scrooge McDuck",
	"Huey, Dewey, and Louie",
	"The Beagle Boys",
	"Magica De Spell",
	"Flintheart Glomgold",
	"Launchpad McQuack",
	"Webby Vanderquack",
	"Mrs. Bentina Beakley",
	"Duckworth the Butler",
	"Marlin",
	"Coral",
	"Nemo",
	"Dory",
	"Bruce, Anchor & Chum",
	"Darla",
	"Gill",
	"Squirt",
	"Crush",
	"Nigel",
	"The Dentist",
	"Zeus",
	"Hercules",
	"Hera",
	"Hermes",
	"Hades",
	"Pain & Panic",
	"Alcmene & Amphitryon",
	"Pegasus",
	"Phil",
	"Megara",
	"Nessus",
	"Mr. Incredible",
	"Elastigirl",
	"Dash",
	"Violet",
	"Jack-Jack",
	"Frozone",
	"Mirage",
	"Edna",
	"Bomb Voyage",
	"Syndrome",
	"Akela",
	"Bagheera",
	"Baloo",
	"Colonel Hathi",
	"Mowgli",
	"Kaa",
	"King Louie",
	"Shanti",
	"Shere Khan",
	"Simba",
	"Scar",
	"Mufasa",
	"Timon and Pumbaa",
	"Nala",
	"Rafiki",
	"Zazu",
	"Shenzi, Banzai and Ed",
	"Sarabi",
	"Sarafina",
	"Kiara",
	"Kovu",
	"Zira",
	"Nuka",
	"Vitani",
	"Ma",
	"Uncle Max",
	"King Triton",
	"Ariel",
	"Flounder",
	"Sebastian",
	"Ariel's Sisters",
	"Prince Eric",
	"Urchin",
	"Evil Manta",
	"Mickey Mouse",
	"Minnie Mouse",
	"Goofy",
	"Pluto",
	"Donald Duck",
	"Daisy Duck",
	"Sully",
	"Randall",
	"Mike",
	"Boo",
	"Mr. Waternoose",
	"Peter Pan",
	"Tinker Bell",
	"John",
	"Wendy",
	"Captain Hook",
	"The Crocodile",
	"George Darling",
	"The Lost Boys",
	"Mary Darling",
	"Michael",
	"Nana",
	"Smee",
	"Tiger Lily",
	"Lost boys",
	"Jiminy Cricket",
	"Pinocchio",
	"Geppetto",
	"Figaro & Cleo",
	"Foulfellow the Fox",
	"Stromboli",
	"Gideon the Cat",
	"The Blue Fairy",
	"Lampwick",
	"Monstro",
	"The Coachman",
	"Governor Ratcliffe",
	"John Smith",
	"Thomas",
	"Pocahontas",
	"Kocoum",
	"Grandmother Willow",
	"Chief Powhatan",
	"Nakoma",
	"Alfredo Linguini",
	"Colette",
	"Emile",
	"Remy",
	"Robin Hood",
	"King Richard",
	"Prince John",
	"Little John",
	"Sheriff of Nottingham",
	"Friar Tuck",
	"Maid Marian",
	"Sir Hiss",
	"Trigger & Nutsey",
	"Skippy",
	"Aurora/Briar Rose",
	"King Stefan",
	"Queen Leah",
	"Prince Philip",
	"King Hubert",
	"Fauna, Flora & Merryweather",
	"Maleficent",
	"Diablo the Raven",
	"Snow White and the Seven Dwarfs",
	"Bashful",
	"Doc",
	"Dopey",
	"Grumpy",
	"Happy",
	"The Magic Mirror",
	"The Prince",
	"Queen",
	"Sleepy",
	"Sneezy",
	"Snow White",
	"Baloo",
	"Kit Cloudkicker",
	"Shere Khan",
	"Louie",
	"Don Karnage",
	"Molly Cunningham",
	"Rebecca Cunningham",
	"Tarzan",
	"Kala & Kerchak",
	"Tantor",
	"Terkina (Terk)",
	"Professor Archimedes Q. Porter",
	"Mr. Clayton",
	"Jane",
	"Al",
	"Andy",
	"Bullseye",
	"Bo Peep",
	"Buzz Lightyear",
	"Ham",
	"Jessie",
	"Mr. & Mrs. Potatohead",
	"Rex",
	"Sarge",
	"Sid",
	"Slinky",
	"Stinky Pete, the prospector",
	"Wheezy",
	"Woody",
	"Winnie the Pooh",
	"Piglet",
	"Rabbit",
	"Tigger",
	"Eeyore",
	"Kanga & Roo",
	"Lumpy",
	"Vito Corleone",
	"James Bond",
	"Indiana Jones",
	"Darth Vader"
];